"""
- name: Include variables from file
  include_vars:
    file: vars.yaml
    name: vars
"""

- name: Test connection
  ping:
    data: pong

- name: Install codeserver
  shell:
    cmd: "curl -fsSL https://code-server.dev/install.sh | sh"

# - name: Install codeserver
#   shell: "curl -fOL https://github.com/cdr/code-server/releases/download/v3.10.2/code-server_3.10.2_amd64.deb && sudo dpkg -i code-server_3.10.2_amd64.deb"

- name: Copy systemd service file to server
  copy:
    src: codeserver.service
    dest: /etc/systemd/system
    owner: root
    group: root
  become: yes
  notify:
    - Start code-server
